// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5CILlfQeVzJlGHfIy098ndEZV2Jefp6k',
    appId: '1:985485403928:web:73809ab55fcfd76537606d',
    messagingSenderId: '985485403928',
    projectId: 'com-cargoind-app',
    authDomain: 'com-cargoind-app.firebaseapp.com',
    storageBucket: 'com-cargoind-app.firebasestorage.app',
    measurementId: 'G-P2RP3ENWC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApmTIJ7SEjOwGXcby_HQ90oy0sbUIJUms',
    appId: '1:985485403928:android:e6b1c2639f6cc48037606d',
    messagingSenderId: '985485403928',
    projectId: 'com-cargoind-app',
    storageBucket: 'com-cargoind-app.firebasestorage.app',
  );
}
